In [24]:
import requests
from bs4 import BeautifulSoup
import re
import datetime

In [7]:
res = requests.get("https://news.sina.com.cn/")
res.encoding = 'utf-8'
#res.text

In [4]:

soup = BeautifulSoup(res.text, 'html.parser')
#soup.text

In [5]:
#how to get the info generated by JS execution
redballs = soup.select(".redball_big")
blueball = soup.select(".blueball_big")
for redball in redballs:
    print(redball)
print(blueball)

[]

In [6]:
list_14 = soup.select(".list_14")
for list in list_14[0:2]:
    alinks = list.select("a")
    for alink in alinks[0:3]:
        print(alink.text, alink["href"])

上官吉庆辞去西安市市长职务(图/简历) https://news.sina.com.cn/c/2018-11-09/doc-ihmutuea8600305.shtml
美媒：出现多个积极迹象 中美关系即将解冻？ https://news.sina.com.cn/c/2018-11-09/doc-ihnprhzw9606810.shtml
时速4000公里高速列车来了？北京到武汉仅18分钟 https://news.sina.com.cn/c/2018-11-09/doc-ihmutuea8584066.shtml
环球时报：美若踩中国底线 中方反击会毫不迟疑 https://news.sina.com.cn/c/2018-11-09/doc-ihnprhzw6302587.shtml
谁是台湾最大党？台媒：不是国民党也不是民进党 https://news.sina.com.cn/c/2018-11-09/doc-ihmutuea8535404.shtml
马英九提“新三不”原则 蔡英文回应称：扯后腿 https://news.sina.com.cn/o/2018-11-09/doc-ihnprhzw9562213.shtml

In [5]:
newurl = "http://news.sina.com.cn/c/2018-09-12/doc-ihiixzkm7573545.shtml"
res_detail = requests.get(newurl)
res_detail.encoding = "utf-8"
#res_detail.text

In [6]:
soup_detail = BeautifulSoup(res_detail.text, "html.parser")
soup_detail.select(".main-title")[0].text

'尼泊尔不和印度而要赴中国军演 印媒玻璃心碎一地'

In [7]:
timesource = soup_detail.select(".date-source")[0].select(".date")[0].text
timesource

'2018年09月12日 02:24'

In [8]:
from datetime import datetime
dt = datetime.strptime(timesource, "%Y年%m月%d日 %H:%M")
dt

datetime.datetime(2018, 9, 12, 2, 24)

In [9]:
dt.strftime("%Y-%m-%d")

'2018-09-12'

In [10]:
source = soup_detail.select(".date-source")[0].select(".source")[0].text
source

'环球网'

In [11]:
source_link = soup_detail.select(".date-source")[0].select(".source")[0]['href']
source_link

'http://world.huanqiu.com/exclusive/2018-09/12991979.html'

In [12]:
soup_detail.select(".date-source a")[0]['href']

'http://world.huanqiu.com/exclusive/2018-09/12991979.html'

In [76]:
" ".join([p.text.strip() for p in soup_detail.select("#article p")[:-1]])

NameError: name 'soup_detail' is not defined

In [13]:
editor = soup_detail.select("#article p")[-1].text.lstrip("责任编辑：").strip()
editor

'张义凌'

In [14]:
soup_detail.select(".blk-comment")

[<div class="blk-comment" id="wrap_bottom_omment">
 <div class=" sina-comment-wrap" id="bottom_sina_comment">
 </div>
 </div>]

In [15]:
#comments_url = "http://comment5.news.sina.com.cn/page/info?version=1&format=json&channel=gn&newsid=comos-hiixzkm7573545&group=undefined&compress=0&ie=utf-8&oe=utf-8&page=1&page_size=3&t_size=3&h_size=3&thread=1&callback=jsonp_1536849541432&_=1536849541432"
comments_url = "http://comment5.news.sina.com.cn/page/info?version=1&format=json&channel=gn\
&newsid=comos-hiixzkm7573545&group=undefined&compress=0&ie=utf-8&oe=utf-8&page=1&page_size=3\
&t_size=3&h_size=3&thread=12&_=1536849541432"
comment_res = requests.get(comments_url)
comments_result = comment_res.text.strip()
import json
comments_json = json.loads(comments_result)
print(comments_json['result']['count']['total'])
print(comments_json['result']['count']['show'])

462
36

In [67]:
newurl

'http://news.sina.com.cn/c/2018-09-12/doc-ihiixzkm7573545.shtml'

In [70]:
newurl.split('/')[-1].lstrip('doc-i').rstrip('.shtml')

'hiixzkm7573545'

In [16]:
import re
m = re.search('doc-i(.*).shtml', newurl)
m.group(0), m.group(1)

('doc-ihiixzkm7573545.shtml', 'hiixzkm7573545')

In [71]:
dayStart = "2018-01-01"
dayEnd = "2018-01-03"
def get_award_info_between_date(start, end):
    return "http://www.cwl.gov.cn/cwl_admin/kjxx/findDrawNotice?name=ssq&issueCount=&issueStart=&issueEnd=&dayStart=" + start + "&dayEnd="+ end + "&pageNo="

In [72]:
lottery_request = get_award_info_between_date(dayStart, dayEnd)
lottery_request

'http://www.cwl.gov.cn/cwl_admin/kjxx/findDrawNotice?name=ssq&issueCount=&issueStart=&issueEnd=&dayStart=2018-01-01&dayEnd=2018-01-03&pageNo='

In [73]:
lottery_request_headers = {"X-Requested-With":"XMLHttpRequest", 
                           "Referer":"http://www.cwl.gov.cn/kjxx/ssq/kjgg/",
                           "User-Agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36",
                          }

In [74]:
lottery_res = requests.get(lottery_request, headers=lottery_request_headers)
lottery_res, lottery_res.text

(<Response [200]>,
 '{"state":0,"message":"查询成功","pageCount":1,"countNum":1,"Tflag":2,"result":[{"name":"双色球","code":"2018001","detailsLink":"/c/2018-01-02/428659.shtml","videoLink":"/c/2018-01-02/428658.shtml","date":"2018-01-02(二)","week":"二","red":"01,08,11,26,28,31","blue":"04","blue2":"","sales":"367348082","poolmoney":"278621134","content":"黑龙江1注,江苏1注,浙江10注,福建1注,山东1注,湖北2注,湖南1注,广西1注,四川1注,甘肃1注,宁夏1注,深圳1注,共22注。","addmoney":"","addmoney2":"","msg":"","z2add":"","m2add":"","prizegrades":[{"type":1,"typenum":"22","typemoney":"5825255"},{"type":2,"typenum":"191","typemoney":"118819"},{"type":3,"typenum":"2029","typemoney":"3000"},{"type":4,"typenum":"86396","typemoney":"200"},{"type":5,"typenum":"1598202","typemoney":"10"},{"type":6,"typenum":"9974842","typemoney":"5"},{"type":7,"typenum":"","typemoney":""}]}]}')

In [75]:
lottery_json = json.loads(lottery_res.text)
lottery_json

NameError: name 'json' is not defined

In [45]:
lottery_results = []
for item in lottery_json['result']:
    entry = {}
    print(item["code"],item["red"],item["blue"])
    entry["code"] = item["code"]
    entry["red"] = item["red"]
    entry["blue"] = item["blue"]
    lottery_results.append(entry)

2018005 02,20,21,28,31,33 06
2018004 14,18,19,26,30,31 11
2018003 01,14,16,17,20,31 04
2018002 07,18,24,29,31,33 16
2018001 01,08,11,26,28,31 04

In [46]:
import pandas
lottery_df = pandas.DataFrame(lottery_results)
lottery_df.head()

  blue     code                red
0   06  2018005  02,20,21,28,31,33
1   11  2018004  14,18,19,26,30,31
2   04  2018003  01,14,16,17,20,31
3   16  2018002  07,18,24,29,31,33
4   04  2018001  01,08,11,26,28,31

In [47]:
lottery_df.to_csv("lottery.csv")

In [48]:
import sqlite3
with sqlite3.connect("lottery.sqlite") as db:
    lottery_df.to_sql("lottery", con=db)

In [51]:
with sqlite3.connect("lottery.sqlite") as db:
    cs = db.execute("select * from lottery")
    for c in cs:
        print(c)

(0, '06', '2018005', '02,20,21,28,31,33')
(1, '11', '2018004', '14,18,19,26,30,31')
(2, '04', '2018003', '01,14,16,17,20,31')
(3, '16', '2018002', '07,18,24,29,31,33')
(4, '04', '2018001', '01,08,11,26,28,31')

In [77]:
http_url = "http://kaijiang.500.com/shtml/ssq/13075.shtml"
res = requests.get(http_url)
res.encoding = 'gb2312'
#res.text

In [78]:
soup = BeautifulSoup(res.text, 'html.parser')
codes_array = soup.select(".iSelectBox")[0].select("div")[0].select("a")[-2:-1]
for code_item in codes_array:
    print(code_item)
    code = code_item.text
    code_link = code_item["href"]
    print(code + ":" + code_link)

<a href="http://kaijiang.500.com/shtml/ssq/03002.shtml">03002</a>
03002:http://kaijiang.500.com/shtml/ssq/03002.shtml

In [32]:
code = "13075"
detaillink = "http://kaijiang.500.com/shtml/ssq/" + code + ".shtml"
res = requests.get(detaillink)
res.encoding = 'gb2312'
soup = BeautifulSoup(res.text, 'html.parser')

In [48]:
ball_box01 = soup.select(".ball_box01")[0]
ball_reds = ball_box01.select(".ball_red")
reds = []
for ball_red in ball_reds:
    reds.append(ball_red.text.strip())
red = ",".join(reds)
print(red)
ball_blue = ball_box01.select(".ball_blue")[0]
blue = ball_blue.text.strip()
print(blue)

04,06,09,25,30,33
14

In [34]:
date_str = soup.select(".td_title01")[0].select(".span_right")[0].text
print(date_str)
re_res = re.search("开奖日期：(.*) 兑奖截止日期", date_str)
#print(re_res[0])
date_str = re_res[1]

print(date_str)
date_dt = datetime.datetime.strptime(date_str, "%Y年%m月%d日")
date = date_dt.strftime('%Y-%m-%d')
print(date)

开奖日期：2013年6月30日 兑奖截止日期：2013年8月28日
2013年6月30日
2013-06-30

In [47]:
grade1number = grade1money = 0                                                          
grade2number = grade2money = 0                                                          
grade3number = grade3money = 0                                                          
grade4number = grade4money = 0                                                          
grade5number = grade5money = 0                                                          
grade6number = grade6money = 0

table_trs = soup.select(".kj_tablelist02")[1].select("tr")
for table_tds in table_trs[2:-1]:# remove header and footer
    tds = table_tds.select("td")
    (td1,td2,td3) = tds
    (typename, typenumber, typemoney) = (td1.text.strip(), td2.text.strip(), td3.text.strip())
    print((typename, typenumber, typemoney))
    typemoney = typemoney.replace(",", "")
    if typename == '一等奖':
        grade1number = int(typenumber)
        grade1money = int(typemoney)
    elif typename == '二等奖':
        grade2number = int(typenumber)
        grade2money = int(typemoney)
    elif typename == '三等奖':
        grade3number = int(typenumber)
        grade3money = int(typemoney)
    elif typename == '四等奖':
        grade4number = int(typenumber)
        grade4money = int(typemoney)
    elif typename == '五等奖':
        grade5number = int(typenumber)
        grade5money = int(typemoney)
    elif typename == '六等奖':
        grade6number = int(typenumber)
        grade6money = int(typemoney)
    else:
        print("unknown type")

('一等奖', '0', '0')
('二等奖', '47', '656,915')
('三等奖', '1029', '3,000')
('四等奖', '58145', '200')
('五等奖', '1242958', '10')
('六等奖', '9098609', '5')

In [57]:
money_tds = soup.select(".kj_tablelist02")[0].select(".cfont1")
sales = int(money_tds[0].text.strip().replace(",", "")[0:-1])
poolmoney = int(money_tds[1].text.strip().replace(",", "")[0:-1])
print(sales, poolmoney)

358276246 148151453

In [70]:
sequence_balls_td = soup.select(".kj_tablelist02")[0].select("tr")[1].select("tr")[1].select("td")[1]
sequence_balls = sequence_balls_td.text.strip().replace(" ", ",")
print(sequence_balls)

04,09,06,33,25,30